version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash entrypoint.sh
    volumes:
      - .:/app
      - static_volume:/static
      - media_volume:/media
    ports:
      - 8000:8000
    depends_on:
      - db


  db:
    image: postgres:14-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: booster  # Указываем имя базы данных
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123



  # nginx:
  #    build:
  #      context: .
  #      dockerfile: nginx/Dockerfile
  #    ports:
  #      - "80:80"
  #    volumes:
  #     - static_volume:/usr/src/app/static
  #     - media_volume:/usr/src/app/media
  #    depends_on:
  #      - web




volumes:
  db_data:
  static_volume:
  media_volume: