# Generated by Django 4.0.1 on 2024-05-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('is_agreed', models.BooleanField(verbose_name='Соглашение')),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакты',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок Вопроса')),
                ('response', models.TextField(verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery_images/', verbose_name='Картинка')),
                ('to_show', models.BooleanField(verbose_name='Показать')),
            ],
            options={
                'verbose_name': 'Галерея',
                'verbose_name_plural': 'Галереи',
            },
        ),
        migrations.AddIndex(
            model_name='gallery',
            index=models.Index(fields=['id'], name='app_miscell_id_091437_idx'),
        ),
        migrations.AddIndex(
            model_name='faq',
            index=models.Index(fields=['id'], name='app_miscell_id_f65f44_idx'),
        ),
        migrations.AddIndex(
            model_name='faq',
            index=models.Index(fields=['title'], name='app_miscell_title_390750_idx'),
        ),
        migrations.AddIndex(
            model_name='contactus',
            index=models.Index(fields=['id'], name='app_miscell_id_19559f_idx'),
        ),
        migrations.AddIndex(
            model_name='contactus',
            index=models.Index(fields=['title'], name='app_miscell_title_18e7c9_idx'),
        ),
    ]
