# Generated by Django 4.0.1 on 2024-05-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Полное имя')),
                ('image', models.ImageField(upload_to='reviews/', verbose_name='Фотография')),
                ('subtitle', models.CharField(max_length=100, verbose_name='Под Заголовок')),
                ('review_text', models.TextField(verbose_name='Отзыв')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-id'],
            },
        ),
        migrations.AddIndex(
            model_name='reviews',
            index=models.Index(fields=['id'], name='app_reviews_id_beb88e_idx'),
        ),
        migrations.AddIndex(
            model_name='reviews',
            index=models.Index(fields=['full_name'], name='app_reviews_full_na_f2320b_idx'),
        ),
    ]
