# Generated by Django 4.0.1 on 2024-05-05 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutProfession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='major_benefit_images/', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'О Профессии',
                'verbose_name_plural': 'О Профессии',
            },
        ),
        migrations.CreateModel(
            name='ClassesGoing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=25, null=True, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name_plural': 'Как проходят занятия?',
            },
        ),
        migrations.CreateModel(
            name='ClassGoingTopik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='class_going/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name_plural': 'Как проходят занятия?(Топик)',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='course_images/', verbose_name='Картинка')),
                ('extended_image', models.ImageField(upload_to='extended_course_images/', verbose_name='Иконка')),
                ('duration', models.CharField(max_length=255, verbose_name='Продолжительность')),
                ('monthly_price', models.FloatField(verbose_name='Месячная цена')),
                ('discount', models.PositiveIntegerField(verbose_name='Скидка')),
                ('installment_price', models.FloatField(verbose_name='Цена в Рассрочку')),
                ('lesson_duration', models.CharField(max_length=255, verbose_name='Продолжительность урока')),
                ('start_date', models.DateTimeField(verbose_name='Старт Курса')),
                ('timetable', models.CharField(max_length=255, verbose_name='Расписание')),
                ('free_spots', models.IntegerField(verbose_name='Свободные места')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='CourseDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Направление',
                'verbose_name_plural': 'Направления',
            },
        ),
        migrations.CreateModel(
            name='CourseProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовка')),
            ],
            options={
                'verbose_name': 'Программа Курса',
                'verbose_name_plural': 'Программа Курсов',
            },
        ),
        migrations.CreateModel(
            name='CourseTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='teacher_images/', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Преподователь',
                'verbose_name_plural': 'Преподователи',
            },
        ),
        migrations.CreateModel(
            name='EducationBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('image', models.ImageField(upload_to='education_benefit/', verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Плюсы Курса',
                'verbose_name_plural': 'Плюсы Курса',
            },
        ),
        migrations.CreateModel(
            name='MajorBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('image', models.ImageField(upload_to='major_benefit/', verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Плюсы профессии',
                'verbose_name_plural': 'Плюсы профессии',
            },
        ),
        migrations.CreateModel(
            name='OccupationGoing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Заголовок')),
            ],
        ),
        migrations.CreateModel(
            name='ShortOccupationGoing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='occupation_going/', verbose_name='Картинка')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherTechnology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Технологии')),
            ],
            options={
                'verbose_name': 'Технология Преподователя',
                'verbose_name_plural': 'Технологии Преподователей',
            },
        ),
        migrations.CreateModel(
            name='TopicProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Загаловка')),
            ],
            options={
                'verbose_name': 'Тема курса',
                'verbose_name_plural': 'Темы курса(Топик)',
            },
        ),
        migrations.AddIndex(
            model_name='topicprogram',
            index=models.Index(fields=['id'], name='app_courses_id_d09d56_idx'),
        ),
        migrations.AddIndex(
            model_name='topicprogram',
            index=models.Index(fields=['title'], name='app_courses_title_fefe59_idx'),
        ),
        migrations.AddField(
            model_name='teachertechnology',
            name='direction',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app_courses.coursedirection', verbose_name='Напрвление'),
        ),
        migrations.AddField(
            model_name='occupationgoing',
            name='short_occupation_going',
            field=models.ManyToManyField(to='app_courses.ShortOccupationGoing', verbose_name='Ответы как проходят занятия'),
        ),
        migrations.AddIndex(
            model_name='majorbenefit',
            index=models.Index(fields=['id'], name='app_courses_id_172f3c_idx'),
        ),
        migrations.AddIndex(
            model_name='majorbenefit',
            index=models.Index(fields=['title'], name='app_courses_title_55d8da_idx'),
        ),
        migrations.AddIndex(
            model_name='educationbenefit',
            index=models.Index(fields=['id'], name='app_courses_id_fdac7e_idx'),
        ),
        migrations.AddIndex(
            model_name='educationbenefit',
            index=models.Index(fields=['title'], name='app_courses_title_8ab5ee_idx'),
        ),
        migrations.AddField(
            model_name='courseteacher',
            name='technology',
            field=models.ManyToManyField(to='app_courses.TeacherTechnology', verbose_name='Технологии'),
        ),
        migrations.AddField(
            model_name='courseprogram',
            name='course_direction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_courses.coursedirection', verbose_name='Направление Курса'),
        ),
        migrations.AddField(
            model_name='courseprogram',
            name='topic',
            field=models.ManyToManyField(to='app_courses.TopicProgram', verbose_name='Темы'),
        ),
        migrations.AddField(
            model_name='course',
            name='about_profession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_courses.aboutprofession', verbose_name='О профессии'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_program',
            field=models.ManyToManyField(to='app_courses.CourseProgram', verbose_name='Программа курса'),
        ),
        migrations.AddField(
            model_name='course',
            name='direction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_courses.coursedirection', verbose_name='Направление'),
        ),
        migrations.AddField(
            model_name='course',
            name='education_benefit',
            field=models.ManyToManyField(to='app_courses.EducationBenefit', verbose_name='Плюсы Курса'),
        ),
        migrations.AddField(
            model_name='course',
            name='major_benefit',
            field=models.ManyToManyField(to='app_courses.MajorBenefit', verbose_name='Плюсы профессии'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_courses.courseteacher', verbose_name='Преподователи'),
        ),
        migrations.AddField(
            model_name='classgoingtopik',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_courses.course', verbose_name='Курс'),
        ),
        migrations.AddField(
            model_name='classesgoing',
            name='topik',
            field=models.ManyToManyField(to='app_courses.ClassGoingTopik', verbose_name='Топики (Как проходят курсы)'),
        ),
        migrations.AddField(
            model_name='aboutprofession',
            name='major_benefit',
            field=models.ManyToManyField(to='app_courses.MajorBenefit', verbose_name='Плюсы профессии'),
        ),
        migrations.AddField(
            model_name='aboutprofession',
            name='major_education',
            field=models.ManyToManyField(to='app_courses.EducationBenefit', verbose_name='Плюсы Курса'),
        ),
        migrations.AddIndex(
            model_name='courseteacher',
            index=models.Index(fields=['id'], name='app_courses_id_aae462_idx'),
        ),
        migrations.AddIndex(
            model_name='courseteacher',
            index=models.Index(fields=['first_name'], name='app_courses_first_n_46e6bd_idx'),
        ),
        migrations.AddIndex(
            model_name='courseprogram',
            index=models.Index(fields=['id'], name='app_courses_id_341a4a_idx'),
        ),
        migrations.AddIndex(
            model_name='courseprogram',
            index=models.Index(fields=['title'], name='app_courses_title_a45f60_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['id'], name='app_courses_id_6ef077_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['title'], name='app_courses_title_a94ed3_idx'),
        ),
        migrations.AddIndex(
            model_name='aboutprofession',
            index=models.Index(fields=['id'], name='app_courses_id_251bca_idx'),
        ),
        migrations.AddIndex(
            model_name='aboutprofession',
            index=models.Index(fields=['title'], name='app_courses_title_2121ac_idx'),
        ),
    ]
